### ISSUE TITLE
How to link to cuDNN?

### ISSUE THREAD

**Issue by wangkuiyi** [CMakeHub/bazel.cmake#24]
I noticed that nv_library 

https://github.com/gangliao/bazel.cmake/blob/e6049b43e732ce6af3b5191db39b4eba2987d5ec/cmake/bazel.cmake#L137

calls cuda_add_library

https://github.com/gangliao/bazel.cmake/blob/e6049b43e732ce6af3b5191db39b4eba2987d5ec/cmake/bazel.cmake#L72

which adds dependencies to libcuda.a.

However, it doesn't links to libcudnn.a.

Do I have to describe cudnn as a CMake target before I can make it a dependency in nv_library calls? If so, how can I do it?

**Comment by wangkuiyi** [comment]
Oh. I just realized that I can refer to https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/cudnn.cmake

**Comment by gangliao** [comment]
caffe2's cudnn.cmake is also good. https://github.com/facebookresearch/Detectron/blob/master/cmake/legacy/Modules/FindCuDNN.cmake

@wangkuiyi 
In PaddlePaddle, we don't link `cudnn` explicitly, thus there is no cc_library(... DEPS cudnn). Instead, we use `dlopen` to load it at runtime.

https://github.com/PaddlePaddle/Paddle/blob/60647c9aa48296d746b89ee68198f7f36db7b154/paddle/fluid/platform/dynload/cudnn.h#L33-L46

**Comment by gangliao** [comment]
If you don't want to use `dlopen` solution, we can make a `cuDNN` CMake target, you can refer to `external/cuda.cmake` in bazel.cmake. 

https://github.com/gangliao/bazel.cmake/blob/916054d0efcaa388a9b7517b5667a1b5d16182a9/cmake/external/cuda.cmake#L15-L35

**Comment by wangkuiyi** [comment]
Nice! I don't want the dlopen solution at all!

It seems that I should combine the FindCuDNN.cmake from Facebook and the cuda.cmake from bazel.cmake, right?

**Comment by gangliao** [comment]
Exactly. 

```cmake
find_package(cudnn QUIET)

IF(CUDNN_FOUND)
  ADD_LIBRARY(cudnn SHARED IMPORTED GLOBAL) 
  SET_PROPERTY(TARGET cudnn PROPERTY IMPORTED_LOCATION ${CUDNN_LIBRARY})
ENDIF(CUDNN_FOUND)
```
